### ISSUE TITLE
Consider using .insertAdjacentHTML

### ISSUE THREAD

**Issue by Sophievanderburg** [basv1996/web-app-from-scratch-2122#5]
https://github.com/basv1996/web-app-from-scratch-2122/blob/1ba0081dc825057d8873db144651b993506506b7/spa/scripts/barcodeScanner.js#L41

Consider using ``.insertAdjacentHTML`` instead of  ``.innerHTML``  
[https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML)

**Comment by basv1996** [comment]
Fixxeedd
